# -*- coding: utf-8 -*-
"""Solijonov_M.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrFwVNVNLx2K_ObaJtankX0GPZk7gqSa
"""

import numpy as np

# 1-Massiv yaratamiz.
massiv_1d = np.array([10,11,12,13,14])
massiv_2d = np.array([[10,11,12], [13,14,15]])

# 2-Matematik operatsiyalar.
sum_array = np.sum(massiv_1d)
mean_array = np.mean(massiv_1d)
product_array = np.prod(massiv_1d)

print("1D Massiv: ", massiv_1d)
print("2D Massiv: \n ", massiv_2d)
print("Massivlar yig'indisi: ", sum_array)
print("O'rtacha: ", mean_array)
print("Ko'paytma:", product_array)

import pandas as pd

#1.DataFrame yaratish
data = {
    'Ism': ['Muhammad','Javohir','Samandar','Ozodbek','Shoxruh','Sadulla','Anvarjon','Omadbek','Farrux','Sirojiddin'],
    'Yoshi': [19,22,19,19,19,20,19,20,20,19],
    'Shahar': ['Fargona','Fargona','Fargona','Fargona','Fargona','Qoqon','Namangan','Qoqon','Fargona','Andijon']
}

df=pd.DataFrame(data)

#2.Ma'lumotlar
print(df)

#3. Filtrlash
young_people = df[df['Yoshi']<20]
print("20 yoshdan kichiklar:\n", young_people)

#4. O'zgartirish
df['Yoshi'] -=1 #har bir shaxs yoshidan 1ni ayirish.
print("Yangilangan dataframe:\n", df)

# 5. Farg'onaliklarni chiqarish
fargonaliklar = df[df['Shahar'] == 'Fargona']
print("Farg'onaliklar:\n", fargonaliklar)

#6. Excel formatda saqlash.
df.to_excel('642_23.xlsx', index=True, sheet_name= "642_23")